// IMP Project - Robert Lehmann 2020-2021

#pragma once

#include "CoreMinimal.h"
#include "Blueprint/UserWidget.h"
#include "IMPPreviewPlayerWidget.generated.h"

/* UI Widget that renders a player preview generated by an AIMPPreviewCaptureBase Actor on screen. */
UCLASS()
class IMPBASE_API UIMPPreviewPlayerWidget : public UUserWidget
{
	GENERATED_BODY()
	
public:

	UFUNCTION(BlueprintCallable)
	/* Enable/Disable the render target to capture a live preview. Enable this when previewing and disable it when not to save performance.*/
	void SetCapturePreview(const bool bEnabled);

	UFUNCTION(BlueprintCallable)
	/* Updates the mesh and the preview. */
	void UpdatePreview(class UIMPInventoryItemBase* const Item);

	UFUNCTION(BlueprintCallable)
	/* Rotate the Mesh Preview using the current mouse position */
	void RotateMeshPreview(FVector2D InMouseLocation);

	UFUNCTION(BlueprintCallable)
	/* Engage/Disengage in rotation performed by user input */
	void SetUserRotation(const bool bEnabled, const FVector2D MouseLocationStart);

protected:

	UPROPERTY(meta = (BindWidget))
	class UImage* MeshPreview;

	UPROPERTY(EditDefaultsOnly)
	TSubclassOf<class AIMPPreviewCaptureBase> PreviewActorClass;

	virtual void NativeOnInitialized() override;
	virtual void NativeConstruct() override;
	virtual void NativeDestruct() override;
	virtual FReply NativeOnMouseButtonDown(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;
	virtual FReply NativeOnMouseButtonUp(const FGeometry& InGeometry, const FPointerEvent& InMouseEvent) override;

private:

	UPROPERTY()
	class AIMPPreviewCaptureBase* PreviewActor;

	class FReply OnMouseButton(const bool bClicked);
};
